services:
  mysql:
    image: mysql
    container_name: mysql_dev
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_service
      MYSQL_USER: mahdi
      MYSQL_PASSWORD: mahdi1
